apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  type: NodePort
  selector:
    app: app3
  ports:
  - port: 8086
    protocol: TCP
    nodePort: 30086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  selector:
    matchLabels:
      app: app3
  replicas: 1
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: app3
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
