apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app3
spec:
 replicas: 1
 selector:
   matchLabels:
     app: test-app3
 template:
   metadata:
     labels:
       app: test-app3
   spec:                  
     containers:
     - name: test-app3
       image: core.harbor.domain/blueskytto/test-app@sha256:3b5f8aeda8c395517c9027d4776a106f439fc5424c7c2fa86f1a13775298ada6
       ports:
       - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: test-app3
spec:
  type: ClusterIP
  selector:
    app: test-app3
  ports:
    - port: 8086
      targetPort: 8086
      #nodePort: 30001
